const s=document.createElement('style');s.textContent=`
.auth-particle-canvas{position:absolute;inset:0;z-index:1;width:100%;height:100%;pointer-events:none;opacity:.72}
[data-theme="amber-night"] .auth-particle-canvas{opacity:.78}@media(max-width:600px){.auth-particle-canvas{opacity:.58}}
@media(prefers-reduced-motion:reduce){.auth-particle-canvas{display:none}}`;document.head.appendChild(s)
type P={x:number;y:number;r:number;vx:number;vy:number;a:number;accent:boolean;phase:number}
function particle(w:number,h:number):P{return{x:Math.random()*w,y:Math.random()*h,r:1.2+Math.random()*2.8,vx:(Math.random()-.5)*.12,vy:-.04-Math.random()*.12,a:.24+Math.random()*.34,accent:Math.random()<.35,phase:Math.random()*Math.PI*2}}
function mount(page:HTMLElement){if(page.querySelector('.auth-particle-canvas')||matchMedia('(prefers-reduced-motion:reduce)').matches)return
const canvas=document.createElement('canvas');canvas.className='auth-particle-canvas';canvas.ariaHidden='true';page.insertBefore(canvas,page.querySelector('.auth-card'));const ctx=canvas.getContext('2d',{alpha:true});if(!ctx)return
let w=0,h=0,dpr=1,ps:P[]=[],frame=0,px=0,py=0,tx=0,ty=0
const resize=()=>{const r=page.getBoundingClientRect();w=Math.max(1,r.width);h=Math.max(1,r.height);dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);const n=w<650?14:Math.min(36,Math.round(w/38));ps=Array.from({length:n},()=>particle(w,h))}
const ro=new ResizeObserver(resize);ro.observe(page);resize()
page.addEventListener('pointermove',e=>{const r=page.getBoundingClientRect();tx=(e.clientX-r.left-w/2)/w;ty=(e.clientY-r.top-h/2)/h},{passive:true});page.addEventListener('pointerleave',()=>{tx=0;ty=0},{passive:true})
const draw=()=>{if(!page.isConnected){ro.disconnect();cancelAnimationFrame(frame);return}frame=requestAnimationFrame(draw);if(document.hidden)return;px+=(tx-px)*.035;py+=(ty-py)*.035;ctx.clearRect(0,0,w,h);const accent=getComputedStyle(document.documentElement).getPropertyValue('--accent').trim()||'#c9233f';const dark=document.documentElement.getAttribute('data-theme')==='amber-night'
ps.forEach((p,i)=>{p.phase+=.008;p.x+=p.vx+Math.sin(p.phase)*.025+px*(p.accent?-.14:.08);p.y+=p.vy+py*.05;if(p.y < -12){p.y=h+12;p.x=Math.random()*w}if(p.x < -12)p.x=w+12;if(p.x>w+12)p.x=-12;const pulse=.72+Math.sin(p.phase*1.7)*.28;ctx.beginPath();ctx.arc(p.x,p.y,p.r*pulse,0,Math.PI*2);ctx.fillStyle=p.accent?accent:(dark?`rgba(255,255,255,${p.a})`:`rgba(48,51,58,${p.a})`);ctx.globalAlpha=p.accent?p.a*.82:p.a;ctx.fill();if(i%6===0){ctx.beginPath();ctx.arc(p.x,p.y,p.r*4.8,0,Math.PI*2);const g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,p.r*4.8);g.addColorStop(0,p.accent?accent:(dark?'rgba(255,255,255,.4)':'rgba(48,51,58,.28)'));g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.globalAlpha=.16;ctx.fill()}});ctx.globalAlpha=1};frame=requestAnimationFrame(draw)}
function all(){document.querySelectorAll<HTMLElement>('.auth-page').forEach(mount)}new MutationObserver(all).observe(document.body,{childList:true,subtree:true});all();export {}
