import { createContext, useCallback, useContext, useState, type ReactNode } from 'react'

// ── Translations ───────────────────────────────────────────────

export type Lang = 'pt' | 'en'

const translations: Record<Lang, Record<string, string>> = {
  pt: {
    // ── Sidebar ────────────────────────────────────────────────
    'nav.workspace':   'Workspace',
    'nav.account':     'Conta',
    'nav.calendar':    'Calendário',
    'nav.dashboard':   'Dashboard',
    'nav.charts':      'Gráficos',
    'nav.profile':     'Meu Perfil',
    'nav.appearance':  'Aparência',
    'nav.settings':    'Configurações',

    // ── Common ─────────────────────────────────────────────────
    'common.save':       'Salvar',
    'common.saving':     'Salvando…',
    'common.cancel':     'Cancelar',
    'common.edit':       'Editar',
    'common.delete':     'Excluir',
    'common.active':     'Ativo',
    'common.inactive':   'Inativo',
    'common.loading':    'Carregando…',
    'common.error.load': 'Não foi possível carregar',
    'common.error.conn': 'Verifique sua conexão e recarregue a página.',
    'common.no_data':    'Sem dados',

    // ── Settings page ──────────────────────────────────────────
    'cfg.title':              'Configurações',
    'cfg.sub':                'Preferências e ajustes do aplicativo',
    'cfg.section.general':    'Geral',
    'cfg.section.data':       'Dados',
    'cfg.lang.title':         'Idioma',
    'cfg.lang.desc':          'Idioma da interface do aplicativo',
    'cfg.lang.pt':            'Português (Brasil)',
    'cfg.lang.en':            'English',
    'cfg.notif.title':        'Notificações',
    'cfg.notif.desc':         'Lembretes diários de tarefas',
    'cfg.notif.time':         'Horário do lembrete',
    'cfg.notif.enable':       'Ativar notificações',
    'cfg.notif.request':      'Solicitar permissão',
    'cfg.notif.granted':      'Permissão concedida',
    'cfg.notif.blocked':      'Bloqueado pelo navegador',
    'cfg.notif.unsupported':  'Não suportado',
    'cfg.notif.hint':         'Funciona somente enquanto o app estiver aberto no navegador.',
    'cfg.export.title':       'Exportar dados',
    'cfg.export.desc':        'Baixar histórico de tarefas em CSV',
    'cfg.export.btn':         'Baixar CSV',
    'cfg.export.ok':          'Baixado!',
    'cfg.export.hint':        'Exporta todas as suas tarefas compatível com Excel.',

    // ── Conta page ─────────────────────────────────────────────
    'conta.title':            'Minha Conta',
    'conta.sub':              'Gerencie seu perfil e segurança',
    'conta.section.profile':  'Perfil',
    'conta.section.security': 'Segurança',
    'conta.section.session':  'Sessão',
    'conta.avatar.change':    'Alterar foto',
    'conta.avatar.remove':    'Remover foto',
    'conta.avatar.removing':  'Removendo…',
    'conta.avatar.save':      'Salvar foto',
    'conta.avatar.saving':    'Enviando…',
    'conta.avatar.selected':  'Foto selecionada:',
    'conta.avatar.err.upload':'Erro ao enviar foto',
    'conta.avatar.err.remove':'Erro ao remover foto',
    'cropper.title':          'Ajustar foto',
    'cropper.hint':           'Arraste para mover · Scroll / pinça para zoom',
    'cropper.use':            'Usar foto',
    'conta.label.name':       'Nome',
    'conta.label.email':      'E-mail',
    'conta.label.pwd.current':'Senha atual',
    'conta.label.pwd.new':    'Nova senha',
    'conta.label.pwd.confirm':'Confirmar nova senha',
    'conta.ph.name':          'Seu nome',
    'conta.ph.pwd':           '••••••••',
    'conta.ph.pwd.new':       'mín. 8 caracteres',
    'conta.pwd.title':        'Alterar senha',
    'conta.pwd.desc':         'Defina uma nova senha de acesso',
    'conta.pwd.btn':          'Alterar senha',
    'conta.pwd.ok':           'Senha alterada com sucesso ✓',
    'conta.profile.ok':       'Perfil atualizado ✓',
    'conta.logout.title':     'Sair da conta',
    'conta.logout.desc':      'Encerra sua sessão neste dispositivo',
    'conta.logout.btn':       'Sair',
    'conta.pwd.weak':         'Fraca',
    'conta.pwd.medium':       'Média',
    'conta.pwd.good':         'Boa',
    'conta.pwd.strong':       'Forte',
    'conta.err.profile':      'Erro ao salvar perfil',
    'conta.err.pwd':          'Erro ao alterar senha',

    // ── Dashboard page ─────────────────────────────────────────
    'dash.title':              'Dashboard',
    'dash.sub':                'Visão geral do seu desempenho',
    'dash.metric.score':       'Score hoje',
    'dash.metric.streak':      'Streak atual',
    'dash.metric.tasks':       'Tarefas este mês',
    'dash.metric.rate':        'Taxa de conclusão',
    'dash.metric.rate.sub':    'Média mensal do desempenho',
    'dash.score.great':        'Ótimo desempenho!',
    'dash.score.ok':           'Continue assim',
    'dash.score.low':          'Você consegue mais',
    'dash.score.none':         'Sem tarefas hoje',
    'dash.streak.sub':         'Dias consecutivos ≥ 50%',
    'dash.streak.none':        'Complete hoje para começar',
    'dash.streak.day':         'dia',
    'dash.streak.days':        'dias',
    'dash.tasks.sub':          'positivas concluídas',
    'dash.chart.title':        'Desempenho — últimos 30 dias',
    'dash.chart.hint':         'Linha tracejada = meta de 50%',
    'dash.trend.up':           'Melhorando',
    'dash.trend.down':         'Piorando',
    'dash.trend.stable':       'Estável',
    'dash.tooltip.none':       'Sem dados',
    'dash.tooltip.good':       'Bom dia',
    'dash.tooltip.avg':        'Dia médio',
    'dash.tooltip.bad':        'Dia difícil',
    'dash.heatmap.title':      'Histórico de atividade',
    'dash.heatmap.empty':      'Nenhum dado ainda — complete tarefas para ver o histórico.',
    'dash.weekday.title':      'Ritmo semanal',
    'dash.weekday.hint':       'Média de desempenho por dia da semana (últimos 30 dias)',
    'dash.weekday.days':       'registros',
    'dash.weekdays':           'Dom,Seg,Ter,Qua,Qui,Sex,Sáb',

    // ── Gráficos page ──────────────────────────────────────────
    'graficos.title':          'Gráficos',
    'graficos.sub':            'Seu desempenho ao longo do tempo',
    'graficos.section':        'Desempenho mensal',
    'graficos.avg':            'Média do ano',
    'graficos.best':           'Melhor mês',
    'graficos.worst':          'Pior mês',
    'graficos.legend.good':    'Bom (≥70%)',
    'graficos.legend.avg':     'Médio (40–69%)',
    'graficos.legend.low':     'Baixo (<40%)',
    'graficos.legend.none':    'Sem dados',
    'graficos.empty.title':    'Ainda sem dados',
    'graficos.empty.desc':     'Complete tarefas ao longo do mês para ver seu desempenho aqui.',
    'graficos.error.title':    'Erro ao carregar',
    'graficos.error.desc':     'Não foi possível buscar os dados. Tente recarregar a página.',
    'graficos.tooltip.good':   'Excelente',
    'graficos.tooltip.avg':    'Regular',
    'graficos.tooltip.low':    'Baixo',
    'graf.insights.title':     'Visão anual',
    'graf.insights.recorded':  'Meses registrados',
    'graf.insights.recorded.sub': 'com dados',
    'graf.insights.great':     'Meses excelentes',
    'graf.insights.consistency':  'Consistência',
    'graf.insights.consistency.sub': 'média geral',
    'graf.insights.trend':     'Tendência anual',
    'graf.insights.trend.sub': 'vs. início do ano',
    'graf.trend.up':           '↑ Melhorando',
    'graf.trend.down':         '↓ Caindo',
    'graf.trend.stable':       '→ Estável',
    'graf.trend.na':           '— Sem dados',
    'graf.dist.title':         'Distribuição de desempenho',
    'graf.dist.great':         'Excelente',
    'graf.dist.avg':           'Regular',
    'graf.dist.low':           'Baixo',
    'graf.dist.none':          'Sem dados',
    'graf.dist.month':         'mês',
    'graf.dist.months':        'meses',
    'graficos.tooltip.good':   'Bom desempenho',
    'graficos.tooltip.avg':    'Desempenho médio',
    'graficos.tooltip.low':    'Abaixo da meta',

    // ── Personalizar page ──────────────────────────────────────
    'appear.title':            'Personalizar',
    'appear.sub':              'Escolha a aparência do aplicativo',
    'appear.dark':             'Temas Escuros',
    'appear.light':            'Temas Claros',
    'appear.active':           'Ativo',

    // ── Recorrentes page ───────────────────────────────────────
    'rec.title':               'Tarefas Recorrentes',
    'rec.sub':                 'Defina tarefas que aparecem automaticamente todos os dias',
    'rec.new.section':         'Nova tarefa recorrente',
    'rec.new.btn':             'Nova tarefa recorrente',
    'rec.ph.title':            'Nome da tarefa recorrente',
    'rec.ph.desc':             'Descrição (opcional)',
    'rec.type.positive':       '↑ Positiva',
    'rec.type.negative':       '↓ Negativa',
    'rec.freq.daily':          'Todo dia',
    'rec.freq.weekly':         'Dias específicos',
    'rec.save':                'Salvar',
    'rec.saving':              'Salvando...',
    'rec.active':              'Ativas',
    'rec.inactive':            'Pausadas',
    'rec.editing':             'Editando',
    'rec.pause':               'Pausar',
    'rec.activate':            'Ativar',
    'rec.daily':               'Todo dia',
    'rec.weekly':              'Semanal',
    'rec.loading':             'Carregando...',
    'rec.empty.title':         'Nenhuma tarefa recorrente ativa',
    'rec.empty.desc':          'Crie uma tarefa recorrente e ela aparecerá automaticamente no calendário todos os dias.',
    'rec.confirm.delete':      'Excluir',
    'rec.day.1':               'Seg',
    'rec.day.2':               'Ter',
    'rec.day.3':               'Qua',
    'rec.day.4':               'Qui',
    'rec.day.5':               'Sex',
    'rec.day.6':               'Sáb',
    'rec.day.7':               'Dom',

    // ── Calendar page ──────────────────────────────────────────
    'cal.title':               'Calendário',
    'cal.sub':                 'Clique em um dia para gerenciar suas tarefas',
    'cal.nav.prev':            'Mês anterior',
    'cal.nav.next':            'Próximo mês',

    // weekday headers (Sun-first order, matching date-fns getDay())
    'cal.wd.sun':              'Dom',
    'cal.wd.mon':              'Seg',
    'cal.wd.tue':              'Ter',
    'cal.wd.wed':              'Qua',
    'cal.wd.thu':              'Qui',
    'cal.wd.fri':              'Sex',
    'cal.wd.sat':              'Sáb',

    // streak badge
    'cal.streak.day':          'dia',
    'cal.streak.days':         'dias',
    'cal.streak.record':       'recorde',

    // task panel — header & list
    'cal.panel.task':          'tarefa',
    'cal.panel.tasks':         'tarefas',
    'cal.panel.score':         'de boas escolhas hoje',
    'cal.panel.loading':       'Carregando tarefas',
    'cal.panel.empty':         'Nenhuma tarefa para este dia.',
    'cal.panel.neg_divider':   'Hábitos a evitar',

    // task panel — form
    'cal.panel.new_task':      'Nova tarefa',
    'cal.panel.positive':      '↑ Positiva',
    'cal.panel.negative':      '↓ Negativa',
    'cal.panel.neg_hint':      'Evitar esse hábito conta como boa escolha',
    'cal.panel.name_ph':       'Nome da tarefa',
    'cal.panel.desc_ph':       'Descrição (opcional)',
    'cal.panel.recurring':     'Tornar tarefa recorrente',
    'cal.panel.daily':         'Diário',
    'cal.panel.weekly':        'Semanal',
    'cal.panel.hint.daily':    'Aparecerá automaticamente todos os dias',
    'cal.panel.hint.wk_empty': 'Selecione ao menos um dia da semana',
    'cal.panel.hint.weekly':   'Aparecerá toda',
    'cal.panel.saving':        'Salvando...',
    'cal.panel.create':        'Criar recorrente',
    'cal.panel.add':           'Adicionar',

    // task item
    'cal.task.pending':        'Pendente',
    'cal.task.done':           'Concluída',
    'cal.task.habit_done':     'Hábito realizado',
    'cal.task.check':          'Marcar',
    'cal.task.uncheck':        'Desmarcar',

    // ── PWA ────────────────────────────────────────────────────
    'pwa.install.title':  'Instalar TaskFlow',
    'pwa.install.desc':   'Adicione à tela inicial para acesso rápido',
    'pwa.install.btn':    'Instalar',
    'pwa.install.later':  'Agora não',
    'pwa.ios.title':      'Adicionar à tela inicial:',
    'pwa.ios.step1':      'Toque em "Compartilhar"',
    'pwa.ios.step2':      'Selecione "Adicionar à Tela Inicial"',
    'pwa.ios.step3':      'Toque em "Adicionar" para confirmar',
    'pwa.offline':        'Sem conexão — usando dados em cache',
    'pwa.online':         'Conexão restaurada',
  },

  en: {
    // ── Sidebar ────────────────────────────────────────────────
    'nav.workspace':   'Workspace',
    'nav.account':     'Account',
    'nav.calendar':    'Calendar',
    'nav.dashboard':   'Dashboard',
    'nav.charts':      'Charts',
    'nav.profile':     'My Profile',
    'nav.appearance':  'Appearance',
    'nav.settings':    'Settings',

    // ── Common ─────────────────────────────────────────────────
    'common.save':       'Save',
    'common.saving':     'Saving…',
    'common.cancel':     'Cancel',
    'common.edit':       'Edit',
    'common.delete':     'Delete',
    'common.active':     'Active',
    'common.inactive':   'Inactive',
    'common.loading':    'Loading…',
    'common.error.load': 'Could not load',
    'common.error.conn': 'Check your connection and reload the page.',
    'common.no_data':    'No data',

    // ── Settings page ──────────────────────────────────────────
    'cfg.title':              'Settings',
    'cfg.sub':                'Application preferences and adjustments',
    'cfg.section.general':    'General',
    'cfg.section.data':       'Data',
    'cfg.lang.title':         'Language',
    'cfg.lang.desc':          'Application interface language',
    'cfg.lang.pt':            'Português (Brasil)',
    'cfg.lang.en':            'English',
    'cfg.notif.title':        'Notifications',
    'cfg.notif.desc':         'Daily task reminders',
    'cfg.notif.time':         'Reminder time',
    'cfg.notif.enable':       'Enable notifications',
    'cfg.notif.request':      'Request permission',
    'cfg.notif.granted':      'Permission granted',
    'cfg.notif.blocked':      'Blocked by browser',
    'cfg.notif.unsupported':  'Not supported',
    'cfg.notif.hint':         'Only works while the app is open in the browser.',
    'cfg.export.title':       'Export data',
    'cfg.export.desc':        'Download task history as CSV',
    'cfg.export.btn':         'Download CSV',
    'cfg.export.ok':          'Downloaded!',
    'cfg.export.hint':        'Exports all your tasks, compatible with Excel.',

    // ── Conta page ─────────────────────────────────────────────
    'conta.title':            'My Account',
    'conta.sub':              'Manage your profile and security',
    'conta.section.profile':  'Profile',
    'conta.section.security': 'Security',
    'conta.section.session':  'Session',
    'conta.avatar.change':    'Change photo',
    'conta.avatar.remove':    'Remove photo',
    'conta.avatar.removing':  'Removing…',
    'conta.avatar.save':      'Save photo',
    'conta.avatar.saving':    'Uploading…',
    'conta.avatar.selected':  'File selected:',
    'conta.avatar.err.upload':'Error uploading photo',
    'conta.avatar.err.remove':'Error removing photo',
    'cropper.title':          'Adjust photo',
    'cropper.hint':           'Drag to move · Scroll / pinch to zoom',
    'cropper.use':            'Use photo',
    'conta.label.name':       'Name',
    'conta.label.email':      'E-mail',
    'conta.label.pwd.current':'Current password',
    'conta.label.pwd.new':    'New password',
    'conta.label.pwd.confirm':'Confirm new password',
    'conta.ph.name':          'Your name',
    'conta.ph.pwd':           '••••••••',
    'conta.ph.pwd.new':       'min. 8 characters',
    'conta.pwd.title':        'Change password',
    'conta.pwd.desc':         'Set a new access password',
    'conta.pwd.btn':          'Change password',
    'conta.pwd.ok':           'Password changed successfully ✓',
    'conta.profile.ok':       'Profile updated ✓',
    'conta.logout.title':     'Sign out',
    'conta.logout.desc':      'Signs you out of this device',
    'conta.logout.btn':       'Sign out',
    'conta.pwd.weak':         'Weak',
    'conta.pwd.medium':       'Medium',
    'conta.pwd.good':         'Good',
    'conta.pwd.strong':       'Strong',
    'conta.err.profile':      'Error saving profile',
    'conta.err.pwd':          'Error changing password',

    // ── Dashboard page ─────────────────────────────────────────
    'dash.title':              'Dashboard',
    'dash.sub':                'Overview of your performance',
    'dash.metric.score':       "Today's Score",
    'dash.metric.streak':      'Current Streak',
    'dash.metric.tasks':       'Tasks this month',
    'dash.metric.rate':        'Completion rate',
    'dash.metric.rate.sub':    'Monthly average performance',
    'dash.score.great':        'Great performance!',
    'dash.score.ok':           'Keep it up',
    'dash.score.low':          'You can do better',
    'dash.score.none':         'No tasks today',
    'dash.streak.sub':         'Consecutive days ≥ 50%',
    'dash.streak.none':        'Complete today to start',
    'dash.streak.day':         'day',
    'dash.streak.days':        'days',
    'dash.tasks.sub':          'positive completed',
    'dash.chart.title':        'Performance — last 30 days',
    'dash.chart.hint':         'Dashed line = 50% target',
    'dash.trend.up':           'Improving',
    'dash.trend.down':         'Declining',
    'dash.trend.stable':       'Stable',
    'dash.tooltip.none':       'No data',
    'dash.tooltip.good':       'Good day',
    'dash.tooltip.avg':        'Average day',
    'dash.tooltip.bad':        'Tough day',
    'dash.heatmap.title':      'Activity history',
    'dash.heatmap.empty':      'No data yet — complete tasks to see your history.',
    'dash.weekday.title':      'Weekly rhythm',
    'dash.weekday.hint':       'Average performance by day of the week (last 30 days)',
    'dash.weekday.days':       'entries',
    'dash.weekdays':           'Sun,Mon,Tue,Wed,Thu,Fri,Sat',

    // ── Gráficos page ──────────────────────────────────────────
    'graficos.title':          'Charts',
    'graficos.sub':            'Your performance over time',
    'graficos.section':        'Monthly performance',
    'graficos.avg':            'Year average',
    'graficos.best':           'Best month',
    'graficos.worst':          'Worst month',
    'graficos.legend.good':    'Good (≥70%)',
    'graficos.legend.avg':     'Average (40–69%)',
    'graficos.legend.low':     'Low (<40%)',
    'graficos.legend.none':    'No data',
    'graficos.empty.title':    'No data yet',
    'graficos.empty.desc':     'Complete tasks throughout the month to see your performance here.',
    'graficos.error.title':    'Error loading',
    'graficos.error.desc':     'Could not fetch data. Try reloading the page.',
    'graficos.tooltip.good':   'Good performance',
    'graficos.tooltip.avg':    'Average performance',
    'graficos.tooltip.low':    'Below target',
    'graf.insights.title':     'Annual overview',
    'graf.insights.recorded':  'Recorded months',
    'graf.insights.recorded.sub': 'with data',
    'graf.insights.great':     'Great months',
    'graf.insights.consistency':  'Consistency',
    'graf.insights.consistency.sub': 'overall average',
    'graf.insights.trend':     'Annual trend',
    'graf.insights.trend.sub': 'vs. start of year',
    'graf.trend.up':           '↑ Improving',
    'graf.trend.down':         '↓ Declining',
    'graf.trend.stable':       '→ Stable',
    'graf.trend.na':           '— No data',
    'graf.dist.title':         'Performance distribution',
    'graf.dist.great':         'Excellent',
    'graf.dist.avg':           'Average',
    'graf.dist.low':           'Low',
    'graf.dist.none':          'No data',
    'graf.dist.month':         'month',
    'graf.dist.months':        'months',

    // ── Personalizar page ──────────────────────────────────────
    'appear.title':            'Appearance',
    'appear.sub':              'Choose the application theme',
    'appear.dark':             'Dark Themes',
    'appear.light':            'Light Themes',
    'appear.active':           'Active',

    // ── Recorrentes page ───────────────────────────────────────
    'rec.title':               'Recurring Tasks',
    'rec.sub':                 'Define tasks that appear automatically every day',
    'rec.new.section':         'New recurring task',
    'rec.new.btn':             'New recurring task',
    'rec.ph.title':            'Recurring task name',
    'rec.ph.desc':             'Description (optional)',
    'rec.type.positive':       '↑ Positive',
    'rec.type.negative':       '↓ Negative',
    'rec.freq.daily':          'Every day',
    'rec.freq.weekly':         'Specific days',
    'rec.save':                'Save',
    'rec.saving':              'Saving...',
    'rec.active':              'Active',
    'rec.inactive':            'Paused',
    'rec.editing':             'Editing',
    'rec.pause':               'Pause',
    'rec.activate':            'Activate',
    'rec.daily':               'Every day',
    'rec.weekly':              'Weekly',
    'rec.loading':             'Loading...',
    'rec.empty.title':         'No active recurring tasks',
    'rec.empty.desc':          'Create a recurring task and it will appear automatically on the calendar every day.',
    'rec.confirm.delete':      'Delete',
    'rec.day.1':               'Mon',
    'rec.day.2':               'Tue',
    'rec.day.3':               'Wed',
    'rec.day.4':               'Thu',
    'rec.day.5':               'Fri',
    'rec.day.6':               'Sat',
    'rec.day.7':               'Sun',

    // ── Calendar page ──────────────────────────────────────────
    'cal.title':               'Calendar',
    'cal.sub':                 'Click on a day to manage your tasks',
    'cal.nav.prev':            'Previous month',
    'cal.nav.next':            'Next month',

    // weekday headers (Sun-first)
    'cal.wd.sun':              'Sun',
    'cal.wd.mon':              'Mon',
    'cal.wd.tue':              'Tue',
    'cal.wd.wed':              'Wed',
    'cal.wd.thu':              'Thu',
    'cal.wd.fri':              'Fri',
    'cal.wd.sat':              'Sat',

    // streak badge
    'cal.streak.day':          'day',
    'cal.streak.days':         'days',
    'cal.streak.record':       'record',

    // task panel — header & list
    'cal.panel.task':          'task',
    'cal.panel.tasks':         'tasks',
    'cal.panel.score':         'good choices today',
    'cal.panel.loading':       'Loading tasks',
    'cal.panel.empty':         'No tasks for this day.',
    'cal.panel.neg_divider':   'Habits to avoid',

    // task panel — form
    'cal.panel.new_task':      'New task',
    'cal.panel.positive':      '↑ Positive',
    'cal.panel.negative':      '↓ Negative',
    'cal.panel.neg_hint':      'Avoiding this habit counts as a good choice',
    'cal.panel.name_ph':       'Task name',
    'cal.panel.desc_ph':       'Description (optional)',
    'cal.panel.recurring':     'Make task recurring',
    'cal.panel.daily':         'Daily',
    'cal.panel.weekly':        'Weekly',
    'cal.panel.hint.daily':    'Will appear automatically every day',
    'cal.panel.hint.wk_empty': 'Select at least one day of the week',
    'cal.panel.hint.weekly':   'Will appear every',
    'cal.panel.saving':        'Saving...',
    'cal.panel.create':        'Create recurring',
    'cal.panel.add':           'Add',

    // task item
    'cal.task.pending':        'Pending',
    'cal.task.done':           'Done',
    'cal.task.habit_done':     'Habit completed',
    'cal.task.check':          'Check',
    'cal.task.uncheck':        'Uncheck',

    // ── PWA ────────────────────────────────────────────────────
    'pwa.install.title':  'Install TaskFlow',
    'pwa.install.desc':   'Add to home screen for quick access',
    'pwa.install.btn':    'Install',
    'pwa.install.later':  'Not now',
    'pwa.ios.title':      'Add to home screen:',
    'pwa.ios.step1':      'Tap "Share"',
    'pwa.ios.step2':      'Select "Add to Home Screen"',
    'pwa.ios.step3':      'Tap "Add" to confirm',
    'pwa.offline':        'No connection — using cached data',
    'pwa.online':         'Connection restored',
  },
}

// ── Context ────────────────────────────────────────────────────

interface LanguageContextValue {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

const STORAGE_KEY = 'app-lang'

function loadLang(): Lang {
  const saved = localStorage.getItem(STORAGE_KEY)
  return saved === 'en' ? 'en' : 'pt'
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(loadLang)

  const setLang = useCallback((l: Lang) => {
    setLangState(l)
    localStorage.setItem(STORAGE_KEY, l)
  }, [])

  const t = useCallback((key: string): string => {
    return translations[lang][key] ?? translations['pt'][key] ?? key
  }, [lang])

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be inside LanguageProvider')
  return ctx
}
